spring:
  datasource:
    username: root
    password: "#gRh1234567890"
    url: jdbc:mysql://localhost:3306/angulardemo
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
# data jpa spec
  jpa:
    
    hibernate:
      ddl-auto: update
      show-sql: true
      